### PR TITLE
Add additional info section

### PR DESCRIPTION
**Pull request by dmitrydao**
## Overview

Add a common section `Additional Information` with missing pages: 
- FAQ
- Glossary
- Workshop Links
- Example Projects

### CODE REVIEW

**Comment by StephenFluin** [comment]
Some of the information on the FAQ is out of date. If we're re-adding links to it, I think we should probably update it at the same time.

**Comment by dmitrydao** [comment]
> Some of the information on the FAQ is out of date. If we're re-adding links to it, I think we should probably update it at the same time.

What is the info that seems outdated? I can only see boxes (Truffle, Hardhat, Brownie) that have a different naming here.

**Comment by StephenFluin** [comment]
@dmitrydao Can you makes sure we are moving forward to a next step on this one?

**Comment by alexroan** [comment]
@dmitrydao bump

**Pull request closed without merging**
