### PR TITLE
Move the WeChat QR code from the home page to the developer comms page.

### PR DESCRIPTION
**Pull request by dwightjl**
- Clean up the homepage: Remove redundant FAQ, Discord, and GitHub links.
- Clean up HTML formatting on the landing pages.
- Adjust CSS to minimize unused space on our landing pages.
- Move the WeChat QR code to the Developer Communications page.

### CODE REVIEW

**Comment by dmitrydao** [comment]
Some thoughts:
- Not sure removing FAQ, Discord is a good idea. It will be hard for people to find our Discord link I think but that's only my opinion. Also, not sure removing Discord from main page is a good idea too. @PatrickAlphaC, @ZakAyesh. What do you think?
- Agreed to move the WeChat QR code to Comms page though.

**Comment by dwightjl** [comment]
> * Not sure removing FAQ, Discord is a good idea.

Sorry I should have added context. We're planning to replace the Discord link with another module later and changing our FAQ as well. Converting this to Draft for now.

**Review by StephenFluin — CHANGES_REQUESTED** [review]
Can we update the visual treatment just a little bit by possibly adding space between the two blocks on the developers comms page? It looks a little funky here.
Screenshot_20210908_085815

**Comment by dwightjl** [comment]
@StephenFluin I modified the CSS for that element. It looks a bit better now. I narrowed down the padding a bit too on these cl boxes.

**Comment by dwightjl** [comment]
Sorry about that. Somehow I reverted my .css changes after testing them locally. I restored the changes. https://deploy-preview-322--dreamy-villani-0e9e5c.netlify.app/docs/developer-communications/

**Review by StephenFluin — APPROVED** [review]

**Pull request merged**
