### PR TITLE
Updated Solidity Price Feeds example (PriceConsumerV3.sol)

### LINKED ISSUE #1112: [Enhancement]: Enhancing the Solidity example for Price Feeds
### What would you like us to improve?

I think this code snippet https://docs.chain.link/data-feeds/price-feeds#solidity can be improved in the `getLatestPrice()` function by moving the comments not on a single line but in each row where it should be placed. Something like that :
```solidity
function getLatestPrice() public view returns (int) {
        (
            /*uint80 roundID*/,
            int price,
            /*uint startedAt*/,
            /*uint timeStamp*/,
            /*uint80 answeredInRound*/
        ) = priceFeed.latestRoundData();
        return price;
    }
```
Nothing amazing, just a little improvement ;)

### How important it is?

Not important, just the code snippet would be more clean so that's easier to use the example.

### PR DESCRIPTION
**Pull request by Xeway**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.Any change needs to be discussed before proceeding.**

## Closing issues

closes #1112

...

## Description

Just a small improvement in the Solidity code example for Price Feeds. The comments are according to me better placed and more easy to read on multiple lines than on a single line. Things are explained in issue #1112.

...

## Changes

- Code snippet improvement => more readable

### CODE REVIEW

**Comment by thedriftofwords** [comment]
Quick update: this PR is failing tests due to how Prettier reformats the code. It forcibly collapses the commented function parameters in undesirable ways. I'm still looking into this with the team because it's not straightforward to override. Thanks for your patience!

**Comment by thedriftofwords** [comment]
@Xeway May I have permission to add a commit to your PR here?

**Review by thedriftofwords — CHANGES_REQUESTED** [review]
Please apply the change in this commit: https://github.com/smartcontractkit/documentation/commit/658240905cf9424941acd776149376c59950652b 

It's a `prettier-ignore` statement that will pass the failing test. My commit shows where to place this statement. Thanks!

**Comment by Xeway** [comment]
Of course you can modify the PR!
Anyway, sorry for the wait, really busy these times.
But I did what you asked, hope this is okay for you.

**Comment by thedriftofwords** [comment]
In the [Vercel deployment]( https://documentation-git-fork-xeway-patch-1-chainlinklabs.vercel.app/data-feeds/price-feeds#solidity), it appears the `//prettier-ignore` statement doesn't show up in the sample code, so that's ideal.

**Review by thedriftofwords — APPROVED** [review]

**Review by aelmanaa — APPROVED** [review]

**Pull request merged**
