### PR TITLE
Add telem ingress config

### PR DESCRIPTION
**Pull request by skubakdj**
Add config vars:

- TELEMETRY_INGRESS_URL
- TELEMETRY_INGRESS_SERVER_PUB_KEY
- TELEMETRY_INGRESS_LOGGING

### CODE REVIEW

**Comment by dmitrydao** [comment]
LGTM

**Review by StephenFluin — APPROVED** [review]

**Comment by StephenFluin** [comment]
@skubakdj this PR is still a draft, but it looks good to go. What will trigger it being ready?

**Comment by skubakdj** [comment]
@StephenFluin kept it as a draft because the new functionality hasn't made its way into a release yet, but otherwise it's good to go. Happy to merge it up now if we want

**Comment by dwightjl** [comment]
@skubakdj where does this stand? Are we ready for review and merge on this PR?

**Comment by skubakdj** [comment]
@dwightjl thanks for the ping! yep, this is ready for review

**Pull request merged**
