### PR TITLE
Update data providers list

### PR DESCRIPTION
**Pull request by dmitrydao**

### CODE REVIEW

**Comment by StephenFluin** [comment]
Have we considered removing this list and pointing folks to market.link?

**Comment by dmitrydao** [comment]
> Have we considered removing this list and pointing folks to market.link?

That's exactly what we did but there are some data providers that are not on market.link so they should be covered as well. If they're not used by anyone, I'm up for removing the list entirely.

**Review by StephenFluin — APPROVED** [review]

**Review by StephenFluin — CHANGES_REQUESTED** [review]
Can we remove the pages we aren't linking to anymore, and add forwards so that users end up on the right place and we don't have two sources of truth?

**Review by StephenFluin — CHANGES_REQUESTED** [review]
The removed files look good but we still need to add 301 redirects. Can you do that in the firebase.json file?

**Review by StephenFluin — APPROVED** [review]

**Pull request merged**
