### PR TITLE
fix scroll error on home page

### PR DESCRIPTION
**Pull request by StephenFluin**

### CODE REVIEW

**Comment by StephenFluin** [comment]
@dwightjl can you take a look?

**Comment by dwightjl** [comment]
> @dwightjl can you take a look?

Yes I listed this for our next meeting. I couldn't identify any scrolling issues with our current site. Can you describe more clearly what issue this PR is fixing?

**Comment by StephenFluin** [comment]
[image: image.png]
Home page has JS errors.

**Review by dwightjl — APPROVED** [review]

**Comment by dwightjl** [comment]
> [image: image.png] Home page has JS errors.

That's my lack of web development instinct showing through.

LGTM

**Pull request merged**
