### PR TITLE
"Get a random number" V2.5 tutorials and 1.1.1 cleanup

### PR DESCRIPTION
**Pull request by thedriftofwords**
- [x] Subscription "Get a random number" (preview: https://documentation-git-fork-thedriftofwords-ran-975a39-chainlinklabs.vercel.app/vrf/v2-5/subscription/get-a-random-number)
- [x] Direct funding "Get a random number" (https://documentation-git-fork-thedriftofwords-ran-975a39-chainlinklabs.vercel.app/vrf/v2-5/direct-funding/get-a-random-number)

Includes the following changes for 1.1.1 package update:
- Unflattened DirectFundingConsumer.sol
- Release note
- Migration page updates

Also: a usability update in DirectFundingConsumer.sol to use the wrapper's separate `requestRandomness` function for native payment, and corresponding migration page updates.

### CODE REVIEW

**Comment by thedriftofwords** [comment]
- [ ] Refs to update: to V2 programmatic subscription page
- [ ] Add V2.5 programmatic subscription within this PR

**Comment by thedriftofwords** [comment]
Testing

- [ ] Subscription on Sepolia, paying w/ LINK
- [ ] Subscription on Avalanche, paying w/ LINK
- [ ] Subscription on Avalanche, paying w/ AVAX
- [ ] Direct funding on Avalanche, paying w/ LINK
- [ ] Direct funding on Avalanche, paying w/ AVAX

**Comment by thedriftofwords** [comment]
Testing paying w/ native on Sepolia: https://sepolia.etherscan.io/address/0xc0dc96a9c1f0e0b988754db5fdcb67f109a2c6a7#readContract

Request successfully submitted but not fulfilled

**Comment by thedriftofwords** [comment]
Updated DirectFundingConsumer.sol and successfully tested payment with LINK and Sepolia ETH here: https://sepolia.etherscan.io/address/0x85ab53039b10c1655c9a17b62018405079c994e4

**Review by dwightjl — APPROVED** [review]

**Pull request merged**
