### PR TITLE
Astro 2

### PR DESCRIPTION
**Pull request by thedriftofwords**
- Upgrade docs to use Astro 2
- Remove trailing slashes from internal links for SEO cleanup

### CODE REVIEW

**Comment by thedriftofwords** [comment]
Reminder: Check for issue mentioned in https://github.com/smartcontractkit/documentation/pull/1206#pullrequestreview-1351728077

**Comment by thedriftofwords** [comment]
Reminder: Update data feeds addresses pages to mdx here. https://github.com/smartcontractkit/documentation/pull/1206#discussion_r1144237439

**Comment by thedriftofwords** [comment]
Needed to upgrade typescript version to resolve this error: https://github.com/withastro/astro/issues/6616

**Review by dwightjl — CHANGES_REQUESTED** [review]
I noticed some build errors that weren't present before. Everything seems to be working fine though.

```
Unable to resolve a renderer that handles this file! With more than one renderer enabled, you should include an import or use a pragma comment.
Add import React from 'react' or /* jsxImportSource: react */ to this file.
```

**Comment by thedriftofwords** [comment]
> 

https://github.com/withastro/astro/issues/4590 suggests that we could specify preact as the `jsxImportSource` in our tsconfig.

**Review by dwightjl — APPROVED** [review]

**Review by fmonper1 — APPROVED** [review]

**Review by aelmanaa — APPROVED** [review]

**Pull request merged**
