### PR TITLE
Filter data feed table

### PR DESCRIPTION
**Pull request by simkasss**
## Relates issues

relates #1384

## Description

The Ethereum Mainnet price feed [table](https://docs.chain.link/data-feeds/price-feeds/addresses#Ethereum%20Mainnet) has been enhanced with filtering by feed category, allowing users to select one category or multiple categories.

## Changes

Added pagination and filtering by data feed category.

### CODE REVIEW

**Comment by simkasss** [comment]
@dwightjl, could you share your opinion on this change? 
Additionally, I could add a search option (either by adding a search field above the table or modifying the search component in the Header) to enable searching for specific price feeds in the table.

**Comment by dwightjl** [comment]
> @dwightjl, could you share your opinion on this change? Additionally, I could add a search option (either by adding a search field above the table or modifying the search component in the Header) to enable searching for specific price feeds in the table.

This change is great and the search works well. Would it be easy to simply list ALL data feeds in one table and add a filter by network? Similar to what you have for the categories, but for each network instead. Ideally we have all data feeds listed in a single table (if performance allows), and let users filter and search to find what they need. Our network selector is just a temporary solution for helping people get the info they need.

We can probably merge this as it is, but if it's not hard to list everything together that would be even better.

**Comment by simkasss** [comment]
@dwightjl , okay, I will do it.

**Comment by dwightjl** [comment]
@simkasss this latest WIP looks great. I like the buttons at the bottom to switch through pages. If we add that, we should allow searching by address and other feed properties as well. Lots of users like to use ctrl+f to search these tables, so the search box should allow equivalent flexability.

Another challenge would be to try and combine all data feed types into one table and have a Data Feed Type dropdown selector.  We would also need a query parameter to allow linking to specific lists, so you might imagine something like `/data-feeds/addresses?network=polygon&feedType=proofofreserve`.  This will add additional complexity because different feed types have unique attributes that need to be displayed. For example, Proof of Reserve feeds have several attributes that are not on any of the other data feeds. Luckily, they are all together in the JSON files that we use as the source for these tables: https://github.com/smartcontractkit/documentation/blob/e6de98f2be7da36191522d9efff05d91443ebb73/src/features/feeds/data/chains.ts#L34C18-L34C80  Also, network and data feed type selectors would need to be greyed-out to indiciate if a type is not available on a specific network. For example, if a user selects Arbitrum and tries to select Proof of Reserve, they should be prevented from doing that because Proof of Reserve feeds are not yet on Arbitrum.

We can add all of that as a followup PR, but feel free to experiment if you want. This is just my long-term plan to have a unified data feeds list that is easy to filter and search. Somewhat like what https://defillama.com/yields has, but thankfully we have far less complexity to deal with.

**Comment by simkasss** [comment]
@dwightjl , can we divide this task into a few pull requests?
- Implement filtering by data feed category and searching by pair.
- Integrate filtering by network and combine all networks into one table. Enhance the search box flexibility.
- Implement filtering by data feed type and combine all data feed types into one table.
- Grey out the feed type/network selectors to indicate if a type is not available on a specific network.

I have just extracted the dropdown menu from the VRF v2 cost calculator to make it reusable in other features. For the next pull request, I will add this dropdown and combine all networks into one table.

**Comment by simkasss** [comment]
> @dwightjl , can we divide this task into a few pull requests?
> 
> * Implement filtering by data feed category and searching by pair.
> * Integrate filtering by network and combine all networks into one table. 
> * Implement filtering by data feed type and combine all data feed types into one table.
> * Grey out the feed type/network selectors to indicate if a type is not available on a specific network.
> 
> I have just extracted the dropdown menu from the VRF v2 cost calculator to make it reusable in other features. For the next pull request, I will add this dropdown and combine all networks into one table.

@dwightjl maybe I should make some modifications so that you can approve this PR? 
Currently, the Mainnet table has been improved by implementing filtering based on data feed category, pagination, and searching by main feed properties:
- Pair name
- Address
- Asset name
- Asset type
- Reserve type (POR)
- Data source (POR)
- Attestation (POR)

The URL is in sync, everything appears to be working correctly to me. Please let me know if I have overlooked anything.

**Comment by dwightjl** [comment]
We're getting build errors on this now: https://github.com/smartcontractkit/documentation/actions/runs/6099817310/job/16552816596?pr=1403

It might be due to some changes in https://github.com/smartcontractkit/documentation/pull/1446

**Comment by simkasss** [comment]
> We're getting build errors on this now: https://github.com/smartcontractkit/documentation/actions/runs/6099817310/job/16552816596?pr=1403
> 
> It might be due to some changes in #1446

I am going to fix it now

**Comment by simkasss** [comment]
@dwightjl it should be working correctly now, It would be perfect if you would check just in case, before merging.

**Review by dwightjl — APPROVED** [review]

**Comment by dwightjl** [comment]
This is great work @simkasss. Thank you so much!

**Pull request merged**
