### PR TITLE
add deviation and heartbeat to contracts

### PR DESCRIPTION
**Pull request by StephenFluin**
Co-authored-by: dmitrydao <dmitrydaopro@gmail.com>

This replaces #144 by fixing OCR feed data and adding a checkbox to optionally show the new information. cc: @dmitrydao

### CODE REVIEW

**Comment by dmitrydao** [comment]
I think the checkbox needs a bit of space from the text on the right.

And also you duplicate the checkbox for each price feed but only the first checkbox on the page actually works, the rest are not responding for hiding/displaying items.

**Comment by StephenFluin** [comment]
@alexroan just reviewed with Dmitry. This should be good to go. Can you take a look?

**Comment by alexroan** [comment]
I can't seem to get this to work locally, getting these errors in the console:
```
GET http://localhost:4200/docs/ethereum-addresses/subscribe.js net::ERR_ABORTED 404 (Not Found) VM303:1
GET http://localhost:4200/addresses/addresses.json 404 (Not Found)(anonymous) @ VM303:1 (anonymous) @ (index):680 localhost/:720 
GET http://localhost:4200/docs/ethereum-addresses/subscribe.js net::ERR_ABORTED 404 (Not Found) VM315:1 
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
```

**Comment by StephenFluin** [comment]
@alexroan  The addresses.json error will show up on the feeds pages if you haven't setup for local feed processing. It's an unfortunate necessity until we can make all of this data more easily accessible by everyone.
https://github.com/smartcontractkit/documentation/blob/main/CONTRIBUTING.md#adding-a-new-chain-feed

The subscription.js error is unrelated and fixed in https://github.com/smartcontractkit/documentation/pull/205/files#diff-cfefb795d4966817b16d6265e4da521b48160b463cbed5374de81591e9fb02dfR44

**Comment by StephenFluin** [comment]
@alexroan ping on this? I just rebased so it's easier to merge.

**Review by alexroan — APPROVED** [review]

**Pull request merged**
