### PR TITLE
add developer tutorials

### PR DESCRIPTION
**Pull request by dmitrydao**

### CODE REVIEW

**Review by PatrickAlphaC — APPROVED** [review]

**Comment by PatrickAlphaC** [comment]
I love this!

Are we going to add 3rd party tutorials as well?

**Comment by PatrickAlphaC** [comment]
Actually, can we add https://blog.chain.link/build-deploy-and-sell-your-own-dynamic-nft/ under VRF?

**Review by dwightjl — APPROVED** [review]
This is excellent. We are planning to more clearly define what types of content belong in our docs vs the blog, but until that gets sorted out this provides a good bridge back to the relevant content that exists on the blog today.

LGTM

**Comment by dwightjl** [comment]
> Actually, can we add https://blog.chain.link/build-deploy-and-sell-your-own-dynamic-nft/ under VRF?

I opened issue https://github.com/smartcontractkit/documentation/issues/310 to make that change and assigned it to myself. PR on the way.

**Pull request merged**
