### PR TITLE
Fix images and hidden properties

### PR DESCRIPTION
**Pull request by dmitrydao**

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Do we all need to be requested reviewers on these?

**Comment by dmitrydao** [comment]
> Do we all need to be requested reviewers on these?

I think it automatically picks you up as you're the code owner.
Will fix that building error soon, didn't notice it failed.

**Comment by PatrickAlphaC** [comment]
> > Do we all need to be requested reviewers on these?
> 
> I think it automatically picks you up as you're the code owner.
> Will fix that building error soon, didn't notice it failed.

Ok, I'll have to filter out my emails. Thanks

**Review by StephenFluin — CHANGES_REQUESTED** [review]
looking really great, can you replace the 7 readme image blocks with pure markdown?

**Review by StephenFluin — APPROVED** [review]

**Pull request merged**
