### PR TITLE
create redirect for example-walkthrough

### LINKED ISSUE #126: End-to-end beginner walkthrough link is broken
https://docs.chain.link/docs/example-walkthrough

### PR DESCRIPTION
**Pull request by dmitrydao**
fixes #126

### CODE REVIEW

**Comment by StephenFluin** [comment]
Is this the right link? On the archive this URL forwards to the intermediate tutorial.

https://archive.docs.chain.link/docs/example-walkthrough

**Comment by dmitrydao** [comment]
> Is this the right link? On the archive this URL forwards to the intermediate tutorial.
> 
> https://archive.docs.chain.link/docs/example-walkthrough

I think it is the right link. I recall the actual page that contained `example-walktrough` had what we have in those 3 tutorials. You can find that if you login in the readme.

**Review by StephenFluin — CHANGES_REQUESTED** [review]
fix typo in commit message
forward to intermediates tutorial

**Comment by StephenFluin** [comment]
can you make sure to fix the typo in the commit message?

**Review by StephenFluin — APPROVED** [review]

**Pull request merged**
