### PR TITLE
Update names and links for starter kits 

### PR DESCRIPTION
**Pull request by pappas999**
- Update the Chainlink docs to reflect new name for the starter kits, plus the agreed new links to the truffle & hardhat starter kits. Brownie URL needs to stay the same.

- Fixed typo 

**NOTE**: This **cannot** go live until the GitHub updates to the truffle and hardhat starter kits are pushed. I will comment here when these tasks are complete, But raising the PR now for awareness & feedback

### CODE REVIEW

**Comment by alexroan** [comment]
@pappas999, thanks for the clear description. In future, use "Draft Pull Request" when creating placeholder PRs. These can later be set as "Ready for review" when they're ready to be looked at and potentially merged.

**Comment by pappas999** [comment]
Thanks @alexroan , GitHub repos have been updated so this is now ready for review, thanks

**Comment by pappas999** [comment]
Hi @StephenFluin @alexroan , with the starter kit showcase now live, can we please get this reviewed? Thanks

**Comment by StephenFluin** [comment]
The changes look great, but can you please squash the commits into 1?

**Comment by pappas999** [comment]
Hi @StephenFluin , had some issues with the squash, but think I've managed to resolve now into a single commit with just the changes required

**Review by alexroan — APPROVED** [review]

**Pull request merged**
