### PR TITLE
Add Arbitrum mainnet for Data Streams

### PR DESCRIPTION
**Pull request by dwightjl**

### CODE REVIEW

**Review by aelmanaa — APPROVED** [review]

**Review by khadni — APPROVED** [review]

**Comment by Spunsd** [comment]
Yarn

**Comment by Spunsd** [comment]
Thanks

**Comment by Spunsd** [comment]
Stop telling me!

**Comment by Spunsd** [comment]
Thanks

**Review by ClementSutjiatma — DISMISSED** [review]
couple nitpicks:

* Change Data Feed Categories to Data Stream Categories
* fix non-operating Show More Details 

other than that looks good, verified feed id list against internal registry too

**Pull request merged**
